### ISSUE TITLE
gst_query.go:301:9: _Ctype_struct__GstContext can't be allocated in Go; it is incomplete (or unallocatable)

### ISSUE THREAD

**Issue by ll51668** [tinyzimmer/go-gst#1]
![image](https://user-images.githubusercontent.com/30169086/100952415-7f549100-354b-11eb-925d-5b0510a6ebf8.png)
提示不能再Go中创建

**Comment by ll51668** [comment]
> ![图片](https://user-images.githubusercontent.com/30169086/100952415-7f549100-354b-11eb-925d-5b0510a6ebf8.png)
> 提示不能再Go中创造

目前暂时解决修改为：
func (q *Query) ParseContext() *Context {
	var _ctx *C.GstContext
	ctx := C.makeContextWritable(_ctx)

	C.gst_query_parse_context(q.Instance(), &ctx)
	return wrapContext(ctx)
}

**Comment by tinyzimmer** [comment]
will fix  - i have a few projects i need to get back to

**Comment by tinyzimmer** [comment]
fixed
