### ISSUE TITLE
Memory leak when using NewBufferFromBytes?

### ISSUE THREAD

**Issue by vshashi01** [tinyzimmer/go-gst#5]
So based on the current appsrc example, I have been working on tweaking it to use NewBufferFromBytes based on the precalculated pixel buffer. 

The updated NeedDataFunc is as shown below. 

```

src.SetCallbacks(&app.SourceCallbacks{
		NeedDataFunc: func(self *app.Source, _ uint) {

			// If we've reached the end of the palette, end the stream.
			if i == len(palette) {
				src.EndStream()
				return
			}

			fmt.Println("Producing frame:", i)

			// Produce an image frame for this iteration.
			pixels := produceImageFrame(palette[i], width, height)

			// Create a buffer that can hold exactly one video RGBA frame.
			//buf := gst.NewBufferWithSize(videoInfo.Size())
			buf := gst.NewBufferFromBytes(pixels)

			buf.SetPresentationTimestamp(time.Duration(i) * 500 * time.Millisecond)

			buf.Map(gst.MapRead) //in-place of the slow WriteData call. 

			// Push the buffer onto the pipeline.
			self.PushBuffer(buf)

			i++
		},
	})


```

When I ran this, I realized the Memory footprint of the program was steadily increasing as the number of rendered frames was increasing. Am I using this wrappers wrongly? 

I was under the impression that just like usual, calling PushBuffer on the buffer would take ownership of the buffer and free it eventually. Any idea? I looked into the function, to me it looks like the gstreamer C function is also being called as expected. 

The reason I want to avoid WriteData call is its too slow for my purposes.

**Comment by tinyzimmer** [comment]
Thanks for helping so much btw! I really do want to see these bindings to completion and have solid go bindings out there for people to use.

I had caught memory leaks earlier, but had not had time to really dive into where they were coming from. I'm not sure if this is one of the ones I knew about already, or if you found another one. Either way, good to have an issue open to track them.

> I was under the impression that just like usual, calling PushBuffer on the buffer would take ownership of the buffer and free it eventually. Any idea? I looked into the function, to me it looks like the gstreamer C function is also being called as expect

IIRC this is around where I was last time I was looking into it. I couldn't find anywhere I was screwing up, and I was sure gstreamer was doing its job correctly, which led me to want to start digging into what the gotk3 `glib` bindings were doing and possibly utilize Finalizers more. 

For what it's worth, [`memleak.py`  from the `bcc` framework](https://github.com/iovisor/bcc/blob/master/tools/memleak.py) has been super helpful so far in trying to track them down, but it requires a Linux kernel.

**Comment by tinyzimmer** [comment]
The first avenue I'm probably going to go down is to see if runtime finalizers might help. The gotk3 bindings set finalizers on anything that gets sent to them by these bindings. For things that are not GObjects (e.g. buffers) I elected not to at first to see if I could handle things more cleanly. That being said, they may be unavoidable.

I probably won't get a chance to test this until later, but if you want to give it a try yourself, I was going to maybe try replacing `wrapBuffer` in [gst_wrappers.go](https://github.com/tinyzimmer/go-gst/blob/main/gst/gst_wrappers.go#L159) with something like:

```go
func wrapBuffer(buf *C.GstBuffer) *Buffer {
	gobuf := &Buffer{ptr: buf}
	runtime.SetFinalizer(gobuf, func(_ *Buffer) { C.gst_buffer_unref(buf) })
	return gobuf
}
```

I doubt this would break anything, but it _may_ cause a bunch of GST warnings to get logged to the console saying we are unrefing something that doesn't need unrefing. If that happens I'd be back to being confused, because that means gstreamer is definitely doing its part. If it doesn't happen, then it's possible I'm not understanding their documentation correctly, and similar fixes might work for the other memory leaks.

**Comment by tinyzimmer** [comment]
Actually @vshashi01 something I just noticed in your example is that:

```go
buf.Map(gst.MapRead) //in-place of the slow WriteData call. 
```

Might be what is causing your memory leak. I don't think you need it at all, but if you do, you need to make sure to unmap afterwards.

If that isn't it, I guess I'd also be curious if the same thing happens when using `NewBufferFull`. In your example it would be something like:

```go
buf := gst.NewBufferFull(gst.MemoryFlagReadOnly, pixels, len(pixels), 0, len(pixels), func() { fmt.Println("I was destroyed") })
self.PushBuffer(buf)
```

It's virtually the same thing, but you get the extra function that is called so you could debug if the buffer is actually getting destroyed.

**Comment by vshashi01** [comment]
@tinyzimmer Hi thanks for getting back to me. I did end up realizing maybe the mapping of it is not needed at all. tried to create the buffer from bytes and then calling PushBuffer with the buffer. It crashes for me same as NewBufferFull. Calling both of these without mapping it results in a crash for me on Windows. 

Then I started calling buf.Map(gst.Read) just to ensure the memory is mapped before pushing it to PushBuffer, which worked but resulted in a memory leak. I just noticed the memory leak is actually happening on your example as well because the Map function does not set the buffer unmap function in its wrapBuffer function as shown below. 

```
// Map will map the data inside this buffer.
func (b *Buffer) Map(flags MapFlags) *MapInfo {
	var mapInfo C.GstMapInfo
	C.gst_buffer_map(
		(*C.GstBuffer)(b.Instance()),
		(*C.GstMapInfo)(unsafe.Pointer(&mapInfo)),
		C.GstMapFlags(flags),
	)
	return wrapMapInfo(&mapInfo, func() {
		// This may not be necesesary
		// if gobool(C.isBuffer(b.Instance())) {
		// 	C.gst_buffer_unmap(b.Instance(), (*C.GstMapInfo)(unsafe.Pointer(&mapInfo)))
		// }
	})
}

```

You can see above that for some reason you have commented out the finalizer func to unmap it. I am not sure why. 

So what I did was to write an Unmap function to call the C.gst_buffer_unmap, which did the trick and kept the memory consumption at 30 something MB throughout the lifecycle of the app. 

Having said this I need to clarify why I wanted to use NewBufferFromBytes in the first place, the WriteData function is too slow for my use case, hence I wanted to be able to just create the buffer as quickly as possible and push it to the source. Doing this is still crashing for me unless i call Map and Write the pixels anyway on top of the buffers from bytes. 

I get the same behavior when I use gst.NewBufferFull

**Comment by vshashi01** [comment]
For now I gotta continue with the actual project I wanted to use this library for, so I found a work around to write a new function for MapInfo struct that uses C.memcpy to copy the pixels to the buffer after being mapped. I will get back to investigating why pushing the buffer directly without calling to Map is crashing on my machine after that.

**Comment by tinyzimmer** [comment]
I think I remember commenting that out when trying to deal with leaks originally. It was hacky to begin with and not really working well. I think using memcpy for the WriteData would definitely be better than my current implementation though 😆. I'm also curious if just using `buf.FillBytes(0, pixels)` is better too.

I do know I need to go over the examples and make sure they all unmap/unref things correctly when they need to. Some of them skip over the noise just to get to the meat for now.

I am definitely curious to hear more about the crash you are mentioning. Is it a go panic or a gstreamer panic?

That all being said I think I got some homework for now.

**Comment by vshashi01** [comment]
> I think I remember commenting that out when trying to deal with leaks originally. It was hacky to begin with and not really working well. I think using memcpy for the WriteData would definitely be better than my current implementation though 😆. I'm also curious if just using `buf.FillBytes(0, pixels)` is better too.
>

Tried buf.FillBytes as well still crashes for me.
Is there a reason why you didnt explicitly create an Unmap function? I think it makes sense to introduce an Unmap function so that the ppl can call it however they want. God bless memcpy I now can achieve my 30 fps 💯 


> I do know I need to go over the examples and make sure they all unmap/unref things correctly when they need to. Some of them skip over the noise just to get to the meat for now.
> 
Yes good idea. 

> I am definitely curious to hear more about the crash you are mentioning. Is it a go panic or a gstreamer panic?

I dont know. Calling this gives me only an exit code. Which in essence I know is some kind of memory corruption. It would be interesting for you to try it out on your setup as well. If it works fine, then thats another quirk to know about Windows I suppose. 

![image](https://user-images.githubusercontent.com/28664567/103269495-ecdfca00-49f0-11eb-99c9-638c45367a7b.png)

**Comment by tinyzimmer** [comment]
That is bizarre and must be Windows specific. I can't reproduce on nix. That'll be fun.

IIRC it was a conversation with the gstreamer guys on how they did the rust bindings that led me away from doing an explicit Unmap. I was trying to minimize situations where the user had to deal with memory management. I.e. make it more go-ey.

Might be unavoidable though.

**Comment by vshashi01** [comment]
But at this point in time, I think I need someone who understands gstreamer better to be able to identify the root cause of the issue. Will get to it eventually. 

>IIRC it was a conversation with the gstreamer guys on how they did the rust bindings that led me away from doing an explicit Unmap. I was trying to minimize situations where the user had to deal with memory management. I.e. make it more go-ey.
Might be unavoidable though.
>

Indeed, I think the finalizer is probably not a good choice here. It would probably be more confusing to use finalizers simply because of the interoperability between Go and C imo. For now I will stick to the local branch with the Unmap function then.

**Comment by tinyzimmer** [comment]
I'll probably do a branch this evening implementing that and getting rid of the finalizers. I'll highlight you on the PR to see if you have any input. 

I'm curious to see your memcpy coz I do want to get rid of that hacky byte-by-byte implementation. Is it basically just something like?

```go
func (m *MapInfo) WriteData(data []byte) {
	C.memcpy(unsafe.Pointer(m.ptr.data), unsafe.Pointer(&data[0]), C.size_t(len(data)))
}
```

**Comment by vshashi01** [comment]
```
/*
#include "string.h"
#include "gst.go.h"

void copyData (GstMapInfo * mapInfo, void * src, gsize length) { memcpy(mapInfo->data, src, length); }
*/

// CopyData copies the given values directly to the mapped buffer memory.
func (m *MapInfo) CopyData(data []uint8) {
	str := string(data)
	p := unsafe.Pointer(C.CString(str))
	defer C.free(p)

	C.copyData(m.ptr, p, C.gsize(len(str)))
}

```

This is what I did, I was abit conservative in how to pass the pointer because I am not necessarily confident with my own understanding of Go to C interoperability or its memory lifecycle but I think its good to do away with the C function altogether.

**Comment by tinyzimmer** [comment]
This is essentially the same thing, and is almost identical  Basically go throws a header on slices, but you can reliably pass them as the pointer to an array in C by just grabbing the address of the first element in the slice (i.e `&data[0]`). 

What's funny, is this is all very similar to how `BufferFromBytes` works. Except it calls out to gstreamer to do the `memcpy`.

**Comment by tinyzimmer** [comment]
@vshashi01 Three things to note on that PR.

- `Memory` and `Buffer` objects expose an `Unmap` that must be called after doing a `Map`. In my tests so far it seems to do its job correctly even after pushing the buffer onto the pipeline (e.g. able to just use `defer` in the appsrc example and it doesn't cause any errors or apparent leaks). 

- I've done exactly as above with regards to `WriteData`. It _seems_ to work. Curious if it does for you as well and if it takes care of the speed issues. 

- I've rewritten `NewBufferFromBytes` in a way that does not appear to leak, and at least seems to work okay on *nix. Not sure if it will still produce the strange exit code for you though.

**Comment by tinyzimmer** [comment]
I got more context on this issue with the exit code from the IRC channel. 

It seems the bindings can't pass anything to a new wrapped buffer that can't be freed with `g_free()`. It's possible this was working fine on *nix because of the way the go runtime works there, but Windows uses a different default memory allocator that may not have handled the implementation correctly. 

After talking to them though I am more confident that the new implementation will work.
