### ISSUE TITLE
Api to dump pipeline dot files.

### ISSUE THREAD

**Issue by jinleileiking** [tinyzimmer/go-gst#56]
see https://developer.ridgerun.com/wiki/index.php/How_to_generate_a_GStreamer_pipeline_diagram.

**Comment by brucekim** [comment]
go-gst provide the corresponding api like below:

[```
func (b *Bin) DebugBinToDotFile(details DebugGraphDetails, filename string) {
```](https://github.com/tinyzimmer/go-gst/blob/d24532796427d84ab76dcdd45f6ff1d2fe402683/gst/gst_bin.go#L312-L316)

As you refer from the link, in order for that the api call generates .dot file, the env variable below should be set in prior to calling the api:
```
export GST_DEBUG_DUMP_DOT_DIR={specify the path where .dot file would be stored}
```

**Comment by jinleileiking** [comment]
Thanks. @brucekim How can I dump the whole pipeline?
