### ISSUE TITLE
[question] best possible way to make this work together with gotk4 ? 

### ISSUE THREAD

**Issue by c1ngular** [tinyzimmer/go-gst#64]
I am trying to make an customized video player using this project with [gotk4](https://github.com/diamondburned/gotk4) , I could not make it work , tried [gotk4-gstreamer](https://github.com/OmegaRogue/gotk4-gstreamer)  as well , still no avail . 

Could you give me some directions and guidelines on this , I want to use this project to process rtsp streams and output gtk4paintablesinks , then feed it to gotk4 for final UI customization .  Here is a [discussion](https://github.com/diamondburned/gotk4/discussions/100)  as well .

Or do you happen to know any golang GUI toolkit could fit my purpose better or easier ?

Thank you .

**Comment by RSWilli** [comment]
@c1ngular move this issue to https://github.com/go-gst/go-gst (where future development of the bindings will take place) if you think it is necessary.

**Comment by c1ngular** [comment]
@RSWilli  sure

**Comment by c1ngular** [comment]
I will keep this open here as well so people with same needs will know where to look into .
