### ISSUE TITLE
Advice on dynamically changing appsrc pads into muxer?

### ISSUE THREAD

**Issue by darkvertex** [tinyzimmer/go-gst#9]
(This is perhaps more of a gstreamer question than a go-gst question, but since you appear to be deeply familiar with gstreamer maybe you can nudge me in the good direction...)

I have a Go project using gstreamer with multiple video tracks using push-mode "appsrc" components entering an "mpegtsmuxer" component and then some other stuff after it. The pipeline works but I want to be able to change which appsrc elements are connected while the full pipeline is streaming/active. (There is always at least 1 appsrc active.)

Do you think it's doable? I can do it with full separate pipelines but I wanted to do it "_the gstreamer way_". I tried to understand these articles:
https://gstreamer.freedesktop.org/documentation/application-development/advanced/pipeline-manipulation.html
https://gstreamer.freedesktop.org/documentation/application-development/advanced/dparams.html
and it seems like I should be able to "unlink" the pads if I understood the gist of it.

However, when I try unlinking my appsrc's `src` pad from the mpegtsmuxer's `sink_X` my entire pipeline kinda stops. Any idea what I may be missing? I tried sending EOS on the element before unlinking and it didn't help either.

Willing to contribute an example sample to the repo if I succeed at figuring out the correct approach.

**Comment by tinyzimmer** [comment]
To be totally honest, writing these bindings was me wanting to learn GStreamer better. So I am by no means an expert, but I can still try to help.

It sounds doable, but is definitely one of those edge cases where I feel like the core developers push you to write a plugin instead (which the support in the bindings is there now, and I have more examples myself I'll be adding later - definitely not thoroughly tested though). 

I think the meat of what you need to accomplish is [here](https://gstreamer.freedesktop.org/documentation/application-development/advanced/pipeline-manipulation.html?gi-language=c#changing-elements-in-a-pipeline) except in a different order. Where they are showing an example of removing a transforming element, you are trying to hot-swap sources (which is where I think they'd probably say, "go write a plugin"). That being said I don't think it's impossible. 

I think you'd still want the blocking pad probe on the `appsrc` source pad. From that block, send an EOS to the sink pad on the `mpegtsmuxer` where you've installed an event probe which will fire when the data is flushed out of it. Then in the context of that callback, I think is where you could maybe try to replace `appsrc` elements (make sure new one state is synced with parent after adding), unlinking the old one, and linking the new one. 

There is a generic example of probes [here](https://github.com/tinyzimmer/go-gst/blob/main/examples/pad-probes/main.go) but it doesn't cover much of what you need to do here besides just adding the probes themselves. 

I can try to help you through this adventure, but it may get to a point where it'd be easier for me to see some code 😉
